#!/bin/sh

pci_modelchange(){
for i in `lspci | cut -d':' -f4 `; do
  db -q get hw.pci.$i | xargs echo -n
  done
}

# THIS IS NOT USE. ITS HERE TO HELP PORTING TO MEDIATEK.
# REMOVE IN FUTURE WHEN EVERYTHING WORKS.
iopsys_initialize_db() {
	echo "Initializing iopsys db"

	OLDCFERAM="`uci -q get /lib/db/config/hw.board.cferam`"
	if grep -q rootfstype=ubifs /proc/cmdline; then
		NEWCFERAM="`brcm_fw_tool -s -1 update /dev/mtd0`"
		FILESYSTEM="UBIFS"
		BANK="low"
	elif grep -q ubi:rootfs_1 /proc/cmdline; then
		NEWCFERAM="`brcm_fw_tool -s -1 update /dev/mtd1`"
		FILESYSTEM="UBIFS"
		BANK="high"
	else
		NEWCFERAM="`ls /cferam* | awk -F'.' '{print$NF}'`"
		FILESYSTEM="JFFS2"
		grep -q "bank=low" /proc/cmdline && BANK="low" || BANK="high"
	fi

	if [ -f "/lib/db/config/hw" ] && [ "$NEWCFERAM" == "$OLDCFERAM" ]; then
		echo "Static db already initialized"
		IOPVERSION="`cat /lib/db/version/iop_version`"
                uci set /lib/db/config/hw.board.iopVersion="$IOPVERSION"                
                uci commit    

	else
		echo "Setting up static db"
		BOARDID=`cat /proc/nvram/BoardId`
		if [ "$BOARDID" == "96362ADVNgr" ]; then
			BOARDID="DG150R0"
			echo $BOARDID > /proc/nvram/BoardId
		fi
		[ -d "/lib/db/config" ] || mkdir /lib/db/config
		cp /lib/db/boards/$BOARDID /lib/db/config/hw

		echo "Populating dynamic db parameters"
		HARDWARE="`uci get /lib/db/config/hw.board.hardware`"
		SERIALNR="`cat /proc/nvram/SerialNumber`"
		AUTHKEY="`cat /proc/nvram/AuthKey`"
		WPAKEY="`cat /proc/nvram/WpaKey`"
		DSLANNEX="`cat /proc/nvram/dslAnnex`"
		[ "$DSLANNEX" == "B" ] || DSLANNEX="A"
		[ "$(uci get /lib/db/config/hw.board.hasAdsl)" == "1" ] || DSLANNEX=""
		VBID="`cat /proc/nvram/VoiceBoardId`"
		DESKEY="`cat /proc/nvram/DesKey`"
		RFPI="`cat /proc/nvram/rfpi`"
		BOARDID="`cat /proc/nvram/BoardId`"
		BASEMAC="`cat /proc/nvram/BaseMacAddr | tr ' ' ':' | sed 's/:$//' | tr [a-z] [A-Z]`"
		HWMODEL="`cat /lib/db/version/iop_version | cut -d'_' -f1 | cut -d'-' -f2`"
		[ "$(uci get /lib/db/config/hw.board.hasDect)" == "1" ] && DECT="D"
		PCI=$(pci_modelchange)
		ROUTERMODEL="$HARDWARE$DSLANNEX-$HWMODEL$DECT$PCI"
		BRCMVERSION="`cat /etc/banner | grep BrcmRef | awk '{print$3}'`"
		SOCMODEL="`grep "system type" /proc/cpuinfo  | awk '{print$5}'`"
		SOCREVISION="`brcm_fw_tool info -e`"
		CFEVERSION="`fw_printenv -n uboot_version | awk '{print$2}'`"
		KERNELVERSION="`cat /proc/sys/kernel/osrelease`"
		IOPVERSION="`cat /lib/db/version/iop_version`"

		SERIALNR=${SERIALNR// /}
		BASEMAC=${BASEMAC// /}
		RFPI=${RFPI// /}

		case $SERIALNR in
			*[a-z]*|*[A-Z]*|*[0-9]*) SERIALNR=$SERIALNR ;;
			*) SERIALNR="0000000000" ;;
		esac

		case $AUTHKEY in
			*[a-z]*|*[A-Z]*|*[0-9]*) AUTHKEY=$AUTHKEY ;;
			*) AUTHKEY="0000000000000000" ;;
		esac

		case $DESKEY in
			*[a-z]*|*[A-Z]*|*[0-9]*) DESKEY=$DESKEY ;;
			*) DESKEY="0000000000000000" ;;
		esac

		case $WPAKEY in
			*[a-z]*|*[A-Z]*|*[0-9]*) WPAKEY=$(echo $WPAKEY | sed 's/[ \t]*$//') ;;
			*) WPAKEY="00000000" ;;
		esac

		uci set /lib/db/config/hw.board.cferam="$NEWCFERAM"
		uci set /lib/db/config/hw.board.filesystem="$FILESYSTEM"
		uci set /lib/db/config/hw.board.bank="$BANK"
		uci set /lib/db/config/hw.board.hardwareVersion="$HARDWARE$DSLANNEX"
		uci set /lib/db/config/hw.board.serialNumber="$SERIALNR"
		uci set /lib/db/config/hw.board.authKey="$AUTHKEY"
		uci set /lib/db/config/hw.board.wpaKey="$WPAKEY"
		uci set /lib/db/config/hw.board.dslAnnex="$DSLANNEX"
		uci set /lib/db/config/hw.board.VoiceBoardId="$VBID"
		uci set /lib/db/config/hw.board.desKey="$DESKEY"
		uci set /lib/db/config/hw.board.rfpi="$RFPI"
		uci set /lib/db/config/hw.board.boardId="$BOARDID"
		uci set /lib/db/config/hw.board.BaseMacAddr="$BASEMAC"
		uci set /lib/db/config/hw.board.routerModel="$ROUTERMODEL"
		uci set /lib/db/config/hw.board.brcmVersion="$BRCMVERSION"
		uci set /lib/db/config/hw.board.socModel="$SOCMODEL"
		uci set /lib/db/config/hw.board.socRevision="$SOCREVISION"
		uci set /lib/db/config/hw.board.cfeVersion="$CFEVERSION"
		uci set /lib/db/config/hw.board.kernelVersion="$KERNELVERSION"
		uci set /lib/db/config/hw.board.iopVersion="$IOPVERSION"
		uci commit
	fi
}

iopsys_initialize_db_mtk() {
	echo "Initializing iopsys db"

	if [ -f "/lib/db/config/hw" ] ; then
		echo "Static db already initialized"
	else
		echo "Setting up static db"

		if grep -q "ubi0:rootfs_0" /proc/cmdline; then
			BANK="low"
		elif grep -q "ubi0:rootfs_1" /proc/cmdline; then
			BANK="low"
		fi
		FILESYSTEM="UBIFS"


		BOARDID=`cat /proc/cpuinfo  | grep machine | awk '{print $3}'| tr [a-z] [A-Z]`
		[ -d "/lib/db/config" ] || mkdir /lib/db/config
		cp /lib/db/boards/$BOARDID /lib/db/config/hw

		CFEVERSION="`fw_printenv -n uboot_version | awk '{print$2}'`"
		HARDWARE="`uci get /lib/db/config/hw.board.hardware`"
		SERIALNR="`fw_printenv -n serial_number`"
		BASEMAC="`fw_printenv -n ethaddr | tr ' ' ':' | sed 's/:$//' | tr [a-z] [A-Z]`"

		AUTHKEY="`fw_printenv -n auth_key`"
		WPAKEY="`fw_printenv -n wpa_key`"
		DESKEY="`fw_printenv -n des_key`"		

		HWMODEL="`cat /lib/db/version/iop_version | cut -d'_' -f1 | cut -d'-' -f2`"
		ROUTERMODEL="$HARDWARE$DSLANNEX-$HWMODEL$DECT$PCI"

		SOCMODEL="`cat /proc/cpuinfo | grep "system type" | awk '{print $5}'`"
		SOCREVISION="`cat /proc/cpuinfo | grep "system type" | awk '{print $6}' | cut -d: -f2`"

		KERNELVERSION="`cat /proc/sys/kernel/osrelease`"
		IOPVERSION="`cat /lib/db/version/iop_version`"

		SERIALNR=${SERIALNR// /}
		BASEMAC=${BASEMAC// /}

		case $SERIALNR in
			*[a-z]*|*[A-Z]*|*[0-9]*) SERIALNR=$SERIALNR ;;
			*) SERIALNR="0000000000" ;;
		esac

		case $AUTHKEY in
			*[a-z]*|*[A-Z]*|*[0-9]*) AUTHKEY=$AUTHKEY ;;
			*) AUTHKEY="0000000000000000" ;;
		esac

		case $DESKEY in
			*[a-z]*|*[A-Z]*|*[0-9]*) DESKEY=$DESKEY ;;
			*) DESKEY="0000000000000000" ;;
		esac

		case $WPAKEY in
			*[a-z]*|*[A-Z]*|*[0-9]*) WPAKEY=$(echo $WPAKEY | sed 's/[ \t]*$//') ;;
			*) WPAKEY="00000000" ;;
		esac

		uci set /lib/db/config/hw.board.hardwareVersion="$HARDWARE$DSLANNEX"
		uci set /lib/db/config/hw.board.serialNumber="$SERIALNR"
		uci set /lib/db/config/hw.board.authKey="$AUTHKEY"
		uci set /lib/db/config/hw.board.wpaKey="$WPAKEY"
		uci set /lib/db/config/hw.board.filesystem="$FILESYSTEM"
		uci set /lib/db/config/hw.board.bank="$BANK"
		uci set /lib/db/config/hw.board.desKey="$DESKEY"
		uci set /lib/db/config/hw.board.BaseMacAddr="$BASEMAC"
		uci set /lib/db/config/hw.board.routerModel="$ROUTERMODEL"
		uci set /lib/db/config/hw.board.socModel="$SOCMODEL"
		uci set /lib/db/config/hw.board.socRevision="$SOCREVISION"
		uci set /lib/db/config/hw.board.kernelVersion="$KERNELVERSION"
		uci set /lib/db/config/hw.board.cfeVersion="$CFEVERSION"
		uci set /lib/db/config/hw.board.iopVersion="$IOPVERSION"
		uci commit
	fi
}
boot_hook_add preinit_main iopsys_initialize_db_mtk

